"use client";

import html2pdf from "html2pdf.js";
import type { CheatsheetPayload } from "@/lib/types";

export default function Cheatsheet({ payload }: { payload: CheatsheetPayload }) {

  const downloadPDF = () => {
    const element = document.getElementById("pdf-content");
    if (!element) return;

    const opt = {
      margin: [0.5, 0.5, 0.5, 0.5],
      filename: "learnpulse-cheatsheet.pdf",
      image: { type: "jpeg", quality: 0.98 },

      html2canvas: {
        scale: 2,
        useCORS: true,
      },

      jsPDF: {
        unit: "in",
        format: "letter",
        orientation: "portrait",
      },

      pagebreak: {
        mode: ["css", "legacy"], // 🔥 enables multi-page splitting
      }
    };

    html2pdf().set(opt).from(element).save();
  };

  if (!payload.entries?.length) {
    return <p className="text-sm text-slate-400">No entries generated.</p>;
  }

  return (
    <div>
      {/* PDF CONTENT */}
      <div
        id="pdf-content"
        className="bg-white text-black p-8 font-sans"
      >
        {/* Header */}
        <div className="mb-6 border-b pb-4">
          <h1 className="text-3xl font-bold text-gray-900">
            LearnPulse Cheat Sheet
          </h1>
          <p className="text-sm text-gray-500 mt-1">
            AI-generated study summary
          </p>
        </div>

        {/* Entries */}
        <div className="space-y-6">
          {payload.entries.map((e, i) => (
            <div key={i} className="break-inside-avoid">

              {/* Term */}
              <h2 className="text-lg font-semibold text-gray-800">
                {e.term}
              </h2>

              {/* Definition */}
              <p className="text-sm text-gray-600 mt-1 leading-relaxed">
                {e.definition}
              </p>

              {/* Divider */}
              {i !== payload.entries.length - 1 && (
                <div className="border-b mt-4"></div>
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-10 pt-4 border-t text-xs text-gray-400 text-center">
          Generated by LearnPulse
        </div>
      </div>

      {/* BUTTON */}
      <button
        onClick={downloadPDF}
        className="mt-6 px-5 py-2.5 bg-black text-white rounded-lg text-sm font-medium hover:opacity-90 transition"
      >
        Download PDF
      </button>
    </div>
  );
}