import type { DiagramPayload } from "@/lib/types";

export default function Diagram({ payload }: { payload: DiagramPayload }) {
  if (!payload.svg) {
    return (
      <div className="flex items-center justify-center h-32 rounded-lg border-[0.5px] border-slate-200 dark:border-slate-700">
        <p className="text-sm text-slate-400">No diagram generated.</p>
      </div>
    );
  }
  return (
    <div
      className="w-full overflow-auto rounded-lg border-[0.5px] border-slate-200 dark:border-slate-700"
      // SVG is generated by our own backend — safe to render inline
      dangerouslySetInnerHTML={{ __html: payload.svg }}
    />
  );
}
