"use client";

import { useRef } from "react";
import type { DiagramPayload } from "@/lib/types";

export default function Diagram({ payload }: { payload: DiagramPayload }) {
  const containerRef = useRef<HTMLDivElement>(null);

  if (!payload.svg) {
    return (
      <div className="flex items-center justify-center h-32 rounded-xl border border-line bg-surface">
        <p className="text-sm text-dim">No diagram generated.</p>
      </div>
    );
  }

  function downloadPNG() {
    const svgEl = containerRef.current?.querySelector("svg");
    if (!svgEl) return;

    const svgData = new XMLSerializer().serializeToString(svgEl);
    const svgBlob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(svgBlob);

    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = svgEl.viewBox.baseVal.width || 600;
      canvas.height = svgEl.viewBox.baseVal.height || 400;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);
      const a = document.createElement("a");
      a.download = "concept-diagram.png";
      a.href = canvas.toDataURL("image/png");
      a.click();
    };
    img.src = url;
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-end">
        <button
          type="button"
          onClick={downloadPNG}
          className="flex items-center gap-1.5 h-8 px-3 rounded-lg border border-line text-xs text-dim hover:text-ink hover:border-dim/40 transition-all"
        >
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <path d="M6 1v7M3.5 6l2.5 2.5L8.5 6" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M1.5 10h9" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
          </svg>
          Download PNG
        </button>
      </div>
      <div
        ref={containerRef}
        className="w-full overflow-auto rounded-xl border border-line bg-surface p-4"
        /* SVG is generated by our own backend — safe to render inline */
        dangerouslySetInnerHTML={{ __html: payload.svg }}
      />
    </div>
  );
}
